services:
  smokenotes:
    image: ghcr.io/smokenotes/smokenotes:latest
    container_name: smokenotes
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - DATABASE_PATH=/app/data/bbq_sessions.db
      - OPENWEATHER_API_KEY=
      - DEFAULT_ZIP_CODE=
      - TZ=UTC
  #If you're not using a flameboss device you can remove the below configuration and use smokenotes locally.
  smokenotes_mqtt:
    image: ghcr.io/smokenotes/smokenotes_mqtt:latest
    container_name: smokenotes_mqtt
    depends_on:
      - smokenotes
    restart: unless-stopped
    volumes:
      - ./data/:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_PATH=/app/data/bbq_sessions.db
      # For help with these settings see
      #https://support.flameboss.com/support/solutions/articles/14000129040-connect-to-flame-boss-cloud-mqtt-broker
      - MQTT_BROKER=s4.myflameboss.com
      - MQTT_PORT=1883
      - MQTT_USERNAME=
      - MQTT_PASSWORD=
        #if using public cooks change /data to /open
      - MQTT_TOPIC=flameboss/your_flameboss_device_id/send/data

