services:
  smokenotes_mqtt:
    container_name: smokenotes_mqtt
    restart: unless-stopped
    user: "1000:1000"  # This sets the user:group ID to run the container
    volumes:
      - ../data/:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_PATH=/app/data/bbq_sessions.db
      - PUID=1000
      - PGID=1000
      # For help with these settings see
      #https://support.flameboss.com/support/solutions/articles/14000129040-connect-to-flame-boss-cloud-mqtt-broker
      - MQTT_BROKER=s4.myflameboss.com
      - MQTT_PORT=1883
      - MQTT_USERNAME=
      - MQTT_PASSWORD=
        #if using public cooks change /data to /open
      - MQTT_TOPIC=flameboss/your_flameboss_device_id/send/data
    # Optional: expose a port for debugging or metrics
    # ports:
    #   - "5000:5000"
